### ISSUE TITLE
serialize.Executor produces data races

### ISSUE THREAD

**Issue by denis-tingaikin** [edwarnicke/serialize#5]
## Problem

serialize.Executor currently can run tasks from different goroutines that can produce data race conditions.

Sample:

```go
func TestDataRace(t *testing.T) {
	defer goleak.VerifyNone(t, goleak.IgnoreCurrent())
	var e serialize.Executor
	var arr []int
        wg := sync.WaitGroup{}
	go func() {
		for i := 0; i < 10; i++ {
                         wg.Add(1)
			e.AsyncExec(func() {
 
				arr = append(arr, i)
wg.Done()
			})
		}
	}()
	wg.Wait()
}
```

output:
```
 go test ./... --race        
==================
WARNING: DATA RACE
Read at 0x00c000018098 by goroutine 11:
  github.com/edwarnicke/serialize_test.TestDataRace.func1.1()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize_test.go:38 +0x53
  github.com/edwarnicke/serialize.(*Executor).executeJobs.func1()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize.go:108 +0x74

Previous write at 0x00c000018098 by goroutine 8:
  github.com/edwarnicke/serialize_test.TestDataRace.func1()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize_test.go:36 +0x96

Goroutine 11 (running) created at:
  github.com/edwarnicke/serialize.(*Executor).executeJobs()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize.go:106 +0x7f
  github.com/edwarnicke/serialize.(*Executor).process()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize.go:97 +0x2c1

Goroutine 8 (finished) created at:
  github.com/edwarnicke/serialize_test.TestDataRace()
      /Users/user/go/src/github.com/edwarnicke/serialize/serialize_test.go:35 +0x19c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:992 +0x1eb
==================
--- FAIL: TestDataRace (0.00s)
    testing.go:906: race detected during execution of test
FAIL
FAIL    github.com/edwarnicke/serialize 0.690s
FAIL

```

**Comment by edwarnicke** [comment]
Yep... I figured that out yesterday.  While the action from different race conditions is safe as written, the race detector in golang can't tell its safe (including the built in one in map[]).  Working on a revised version that doesn't utilize multiple goroutines for execution.

**Comment by denis-tingaikin** [comment]
@edwarnicke Should I close this patch?  https://github.com/edwarnicke/serialize/pull/6

**Comment by denis-tingaikin** [comment]
> While the action from different race conditions is safe as written, the race detector in golang can't tell its safe

Actually, the current implementation is not safe. I found the next problems of current implementation:
 1. could spawn two goroutines for one exec channel. Look at https://github.com/edwarnicke/serialize/blob/master/serialize.go#L59
https://github.com/edwarnicke/serialize/blob/master/serialize.go#L121
These two conditions could produce one more active goroutine for reading jobs...
 2. backlog jobs are not synchronized between goroutes from problem 1. It's why go detects race.
